# -*- coding: utf-8 -*-
"""ТВиМС 2  практическая работа.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dxgx4Wpb_BaNmQl_ONzCccqBID3BWxXc

Заревич Михаил, 513-2
"""

import pandas as pd
import numpy as np
import itertools
import scipy.stats
import math
import matplotlib.pyplot as plt

"""Документация на pandas.DataFrame https://pandas.pydata.org/pandas-docs/stable/reference/frame.html

Документация на scipy
https://docs.scipy.org/doc/scipy/index.htm

Статистические функции
https://docs.scipy.org/doc/scipy/tutorial/stats.html

Биномиальное распределение https://docs.scipy.org/doc/scipy/tutorial/stats/discrete_binom.html

Распределение Пуассона https://docs.scipy.org/doc/scipy/tutorial/stats/discrete_poisson.html

Нормальное распределение https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.norm.html#scipy.stats.norm
https://pieriantraining.com/working-with-scipy-stats-norm-a-guide/

"""

# Количество экспериментов и шаг увеличения
Nmin = 10
Nmax = 1000
step = 10

# список с количествами экспериментов
ExperimentsNumber = [i for i in range(Nmin, Nmax+1, step)]

# вероятности успеха
prob = [0.0005, 0.005, 0.05, 0.25, 0.5, 0.75, 0.9, 0.95, 0.995, 0.9995]

print(ExperimentsNumber)

# для каждого количества должно быть 10 вероятностей
# experiments number, probability
# создаёт пары вида: количество экспериментов, вероятность успеха
ExNumberProb = itertools.product(ExperimentsNumber, prob)

ColumnNames = [ "Количество опытов, n", "Количество успехов, m", "Вероятность успеха, p", "Вероятность P(X=m) по формуле Бернулли",
                "Вероятность P(X=m) по формуле Пуассона", "Вероятность P(X=m) по формуле нормального распределения",
                "Относительная погрешность биномиального относительно Пуассона", "Относительная погрешность биномиального относительно нормального", "Относительная погрешность Пуассона относительно нормального"]

"""Код, который всё считает и создаёт датафрейм."""

# список из словарей для создания датафрейма
results = []

# пары вида: количество экспериментов, вероятность успеха
# например 10 0.0005
for n, p in ExNumberProb:

    q = 1-p

    # математическое ожидание
    mean = n*p
    # дисперсия
    variance = n*p*q

    # биномиальное распределение
    # binomial distribution
    bd = scipy.stats.binom(n, p)

    # распределение Пуассона
    # Poisson distribution
    # не pd, так как это отвечает за pandas
    poisd = scipy.stats.poisson(mean)

    # нормальное распределение с мат. ожиданием np и ско npq. Второй параметр тут - ско, а не дисперсия
    # normal distribution
    nd = scipy.stats.norm(mean, math.sqrt(variance))

    # i - количество успехов.
    # для 10 опытов это будет от 0 до 10 включительно
    #success number
    for i in range(n+1):

        # вероятности
        # pmf - probability mass function - функция вероятности, для дискретных СВ
        # pdf - probability dencity function - плотность вероятности, для непрерывных СВ
        bd_prob = bd.pmf(i)
        poisd_prob = poisd.pmf(i)
        nd_prob = nd.pdf(i)

        # Более быстрый вариант, который мне показала Софья.
        # Заносить данные в словарь, потом создавать датафрейм из словаря. Таким образом код выполнится примерно за 4 минуты.
        # создание словаря с полученными данными
        data=[n, i, p, bd_prob, poisd_prob, nd_prob, abs((bd_prob-poisd_prob)/bd_prob), abs((bd_prob-nd_prob)/bd_prob), abs((poisd_prob-nd_prob)/poisd_prob)]
        temp = dict(zip(ColumnNames, data))
        results.append(temp)

        # Неправильный вариант.
        # Добавлять данные в датафрейм сразу. Этот вариант выполняется за 29 минут.
        #data=[[n], [i], [p], [bd_prob], [poisd_prob], [nd_prob],  [abs(bd_prob-poisd_prob)], [abs(bd_prob-nd_prob)], [abs(poisd_prob-nd_prob)],[(bd_prob+poisd_prob+nd_prob)/3]]
        # добавляет данные в датафрейм
        #newdf = pd.DataFrame(temp)
        #df = pd.concat([df,newdf], ignore_index=True,  axis = 0)

# создание датафрейма на основе списка словарей.
df = pd.DataFrame(results)

df

# Сохраню этот файл себе, чтобы потом не считать всё снова.
df.to_csv("ТВиМС 2 работа, датафрейм.csv", sep=',', encoding='utf-8') # 67.5 мб
df.to_excel("ТВиМС 2 работа, датафрейм.xlsx") # 39.6 мб

""" Определите попарную относительную погрешность для каждого способа и каждого p. Запишите полученные результаты в
DataFrame. Определите среднюю погрешность и её исправленное среднее квадратическое отклонение для каждой пары n, p.
"""

# Перед тем, как посчитать погрешность, нужно убрать везде inf
# которые возникли из-за того, что, например, для данных вероятностей
# приближение неприменимо, поэтому разброс получился слишком большим
# Если этого не сделать, mean и std тоже будет равно бесконечности.
df_clean_no_inf = df.replace([np.inf, -np.inf], np.nan)

# В этой таблице всё ещё могут быть некоторые inf
# Они возникли из-за того, что некоторые вероятности получились очень маленькими
# т.е у биномиального 1e-50 а у Пуассона 1e-10. Разница между ними, соответственно, очень большая.
# Поэтому где-то тут возникала ошибка RuntimeWarning: overflow encountered in square sqr = _ensure_numeric((avg - values) ** 2)
# говорящая о том, что значение для числового типа данных оказалось слишком большим и оно было переведено в inf
# Чтобы это исправить, нужно убрать слишком маленькие значения
df_clean_clear_no_small_prob= df_clean_no_inf[df_clean_no_inf['Вероятность P(X=m) по формуле Бернулли'] > 1e-10]


# Группировка по арам n и p, и для колонок с погрешностями считаем mean (средняя погрешность) и std (СКО)
error_df = df_clean_clear_no_small_prob.groupby(['Количество опытов, n', 'Вероятность успеха, p'])[[
    'Относительная погрешность биномиального относительно Пуассона',
    'Относительная погрешность биномиального относительно нормального',
     "Относительная погрешность Пуассона относительно нормального"
]].agg(['mean', 'std'])

# Выводим результат
error_df.to_excel("ТВиМС 2 работа, cтатистика погрешностей.xlsx")

error_df

"""# Ответы на контрольные вопросы

## 1 Для каких пар значений n, p применимо приближённое вычисление вероятности при помощи распределения Пуассона?

Распределение Пуассона, вместо биномиального, можно применять, если вероятность успеха p стремится к нулю, а число экспериментов n - к бесконечности.

Убедимся в этом, построив графики биномиального распределения и распределения Пуассона для одних и тех же параметров n и p, а также построим график погрешности между ними.

Из графиков также видно, что приближение хорошо работает в точках, близких к пику биномиального распределения.
"""

current_n = 100
current_p = 0.95


subset = df_clean_no_inf[(df_clean_no_inf["Количество опытов, n"] == current_n) &
                  (df_clean_no_inf["Вероятность успеха, p"] == current_p)]


#subset = subset.sort_values(by="Количество успехов, m")


plt.figure(figsize=(10, 6))

# График биномиального распределения
plt.plot(subset["Количество успехов, m"],
         subset["Вероятность P(X=m) по формуле Бернулли"],
         label="График биномиального распределения",
         color="blue", marker="o", markersize=3, alpha=0.6)

# График распределения Пуассона
plt.plot(subset["Количество успехов, m"],
         subset["Вероятность P(X=m) по формуле Пуассона"],
         label="График распределения Пуассона",
         color="red", linestyle="--", linewidth=2)

plt.title(f"Сравнение распределений при: n={current_n}, p={current_p}")
plt.xlabel("Количество успехов, m")
plt.ylabel("Вероятность события, P(X=m)")
plt.legend()
plt.grid(True, alpha=0.3)

plt.show()


# График погрешности
df1 = df_clean_no_inf[df_clean_no_inf["Количество опытов, n"] == current_n]
df1 = df1[df1["Вероятность успеха, p"] == current_p]

plt.figure(figsize=(10, 6))
plt.plot(df1["Количество успехов, m"], df1["Относительная погрешность биномиального относительно Пуассона"] , label="Относительная погрешность биномиального относительно Пуассона при n = 100, p = 0.95")

plt.title(f"Погрешность при: n={current_n}, p={current_p}")

plt.xlabel("Количество успехов, m")
plt.ylabel("Погрешность")
plt.grid(True, alpha=0.3)

plt.show()

# В диапазоне от 80 до 100 график пошёл слишком низко, по сравнениию с первыми значениями,
# Поэтому я ограничил значения y, чтобы он был более информативным.
df1 = df_clean_no_inf[df_clean_no_inf["Количество опытов, n"] == current_n]
df1 = df1[df1["Вероятность успеха, p"] == current_p]

plt.figure(figsize=(10, 6))
plt.plot(df1["Количество успехов, m"], df1["Относительная погрешность биномиального относительно Пуассона"] , label="Относительная погрешность биномиального относительно Пуассона при n = 100, p = 0.95")

plt.ylim(0, 5)
plt.grid(True, alpha=0.3)

plt.title(f"Погрешность при: n={current_n}, p={current_p}. Другой масштаб y")

plt.xlabel("Количество успехов, m")
plt.ylabel("Погрешность")
plt.grid(True, alpha=0.3)

plt.show()

current_n = 100
current_p = 0.5


subset = df_clean_no_inf[(df_clean_no_inf["Количество опытов, n"] == current_n) &
                  (df_clean_no_inf["Вероятность успеха, p"] == current_p)]


#subset = subset.sort_values(by="Количество успехов, m")


plt.figure(figsize=(10, 6))

# График биномиального распределения
plt.plot(subset["Количество успехов, m"],
         subset["Вероятность P(X=m) по формуле Бернулли"],
         label="График биномиального распределения",
         color="blue", marker="o", markersize=3, alpha=0.6)

# График распределения Пуассона
plt.plot(subset["Количество успехов, m"],
         subset["Вероятность P(X=m) по формуле Пуассона"],
         label="График распределения Пуассона",
         color="red", linestyle="--", linewidth=2)

plt.title(f"Сравнение распределений при: n={current_n}, p={current_p}")
plt.xlabel("Количество успехов, m")
plt.ylabel("Вероятность события, P(X=m)")
plt.legend()
plt.grid(True, alpha=0.3)

plt.show()


# График погрешности
df1 = df_clean_no_inf[df_clean_no_inf["Количество опытов, n"] == current_n]
df1 = df1[df1["Вероятность успеха, p"] == current_p]

plt.figure(figsize=(10, 6))
plt.plot(df1["Количество успехов, m"], df1["Относительная погрешность биномиального относительно Пуассона"] , label="Относительная погрешность биномиального относительно Пуассона при n = 100, p = 0.95")

plt.title(f"Погрешность при: n={current_n}, p={current_p}")

plt.xlabel("Количество успехов, m")
plt.ylabel("Погрешность")
plt.grid(True, alpha=0.3)

plt.show()

# В диапазоне от 80 до 100 график пошёл слишком низко, по сравнениию с первыми значениями,
# Поэтому я ограничил значения y, чтобы он был более информативным.
df1 = df_clean_no_inf[df_clean_no_inf["Количество опытов, n"] == current_n]
df1 = df1[df1["Вероятность успеха, p"] == current_p]

plt.figure(figsize=(10, 6))
plt.plot(df1["Количество успехов, m"], df1["Относительная погрешность биномиального относительно Пуассона"] , label="Относительная погрешность биномиального относительно Пуассона при n = 100, p = 0.95")

plt.ylim(0, 5)
plt.grid(True, alpha=0.3)

plt.title(f"Погрешность при: n={current_n}, p={current_p}. Другой масштаб y")

plt.xlabel("Количество успехов, m")
plt.ylabel("Погрешность")
plt.grid(True, alpha=0.3)

plt.show()

current_n = 100
current_p = 0.05


subset = df_clean_no_inf[(df_clean_no_inf["Количество опытов, n"] == current_n) &
                  (df_clean_no_inf["Вероятность успеха, p"] == current_p)]


#subset = subset.sort_values(by="Количество успехов, m")


plt.figure(figsize=(10, 6))

# График биномиального распределения
plt.plot(subset["Количество успехов, m"],
         subset["Вероятность P(X=m) по формуле Бернулли"],
         label="График биномиального распределения",
         color="blue", marker="o", markersize=3, alpha=0.6)

# График распределения Пуассона
plt.plot(subset["Количество успехов, m"],
         subset["Вероятность P(X=m) по формуле Пуассона"],
         label="График распределения Пуассона",
         color="red", linestyle="--", linewidth=2)

plt.title(f"Сравнение распределений при: n={current_n}, p={current_p}")
plt.xlabel("Количество успехов, m")
plt.ylabel("Вероятность события, P(X=m)")
plt.legend()
plt.grid(True, alpha=0.3)

plt.show()


# График погрешности
df1 = df_clean_no_inf[df_clean_no_inf["Количество опытов, n"] == current_n]
df1 = df1[df1["Вероятность успеха, p"] == current_p]

plt.figure(figsize=(10, 6))
plt.plot(df1["Количество успехов, m"], df1["Относительная погрешность биномиального относительно Пуассона"] , label="Относительная погрешность биномиального относительно Пуассона при n = 100, p = 0.95")

plt.title(f"Погрешность при: n={current_n}, p={current_p}")

plt.xlabel("Количество успехов, m")
plt.ylabel("Погрешность")
plt.grid(True, alpha=0.3)

plt.show()

# В диапазоне от 80 до 100 график пошёл слишком низко, по сравнениию с первыми значениями,
# Поэтому я ограничил значения y, чтобы он был более информативным.
df1 = df_clean_no_inf[df_clean_no_inf["Количество опытов, n"] == current_n]
df1 = df1[df1["Вероятность успеха, p"] == current_p]
#df1 = df1[df1["Количество успехов, m"] > 0]
#df1 = df1[df1["Количество успехов, m"] <30]


plt.figure(figsize=(10, 6))
plt.plot(df1["Количество успехов, m"], df1["Относительная погрешность биномиального относительно Пуассона"] , label="Относительная погрешность биномиального относительно Пуассона при n = 100, p = 0.95")

plt.ylim(0, 5)
plt.grid(True, alpha=0.3)

plt.title(f"Погрешность при: n={current_n}, p={current_p}. Другой масштаб y")

plt.xlabel("Количество успехов, m")
plt.ylabel("Погрешность")
plt.grid(True, alpha=0.3)

plt.show()

"""## Второй вариант ответа

Этот вариант списал в нейросети.

Визуализация функции $mean = f(n,p)$ из данных датафрейма error_df
"""

import seaborn as sns

# Сбрасываем индекс, чтобы n и p стали обычными колонками
viz_data = error_df.reset_index()

# 2. Создаем сводную таблицу для heatmap
# Строки - n, Столбцы - p, Значения - Средняя погрешность
# В values передаем кортеж, чтобы выбрать конкретно среднее значение ('mean')
pivot_table = viz_data.pivot(
    index="Количество опытов, n",
    columns="Вероятность успеха, p",
    values=("Относительная погрешность биномиального относительно Пуассона", "mean")
)

# Рисуем тепловую карту
plt.figure(figsize=(10, 15))
sns.heatmap(pivot_table, annot=True, fmt=".3f", cmap="RdYlGn_r", vmax=1.0)
# vmax=1.0 ограничивает цветовую шкалу: всё, что выше 100% ошибки - красное.
# cmap="RdYlGn_r" - от зеленого (мало ошибок) к красному (много).


plt.title("Средняя относительная погрешность приближения Пуассона")
plt.show()

"""## 2 Для каких пар значений n, p применимо приближённое вычисление вероятности при помощи локальной теоремы Муавра-Лапласа?

см. Гнеденко, стр 96-97
https://psv4.userapi.com/s/v1/d/6NMy4u3YcDHrFFcPKRzzAcW4_7z4LEgd4Q-FoWYiOUUyp_15sYs0xEiCf_TdMsFYwc_Vlf3zcBsJgaKAI0R3-BaNVb6xgdTK2dNGAdpFcBz8K6tHXAvEYw/Gnedenko_B_V_-_Kurs_teorii_veroyatnostey_Izd.pdf

Число n должно быть достаточно большим, больше нескольких сотен, а p - не слишком близким к нулю или единице. Формула работает тем лучше, чем больше n и чем p ближе к 0,5.

Визуализация функции $mean=f(n,p)$  из данных датафрейма error_df. График подтверждает информацию из учебника.
"""

import seaborn as sns

# Сбрасываем индекс, чтобы n и p стали обычными колонками
viz_data = error_df.reset_index()

# 2. Создаем сводную таблицу для heatmap
# Строки - n, Столбцы - p, Значения - Средняя погрешность
# В values передаем кортеж, чтобы выбрать конкретно среднее значение ('mean')
pivot_table = viz_data.pivot(
    index="Количество опытов, n",
    columns="Вероятность успеха, p",
    values=("Относительная погрешность биномиального относительно нормального", "mean")
)

# Рисуем тепловую карту
plt.figure(figsize=(10, 15))
sns.heatmap(pivot_table, annot=True, fmt=".3f", cmap="RdYlGn_r", vmax=1.0)
# vmax=1.0 ограничивает цветовую шкалу: всё, что выше 100% ошибки - красное.
# cmap="RdYlGn_r" - от зеленого (мало ошибок) к красному (много).


plt.title("Средняя относительная погрешность с помощью нормального распределения")
plt.show()

"""Аналогичные резульаты получаются, если зафиксировать значение n и построить графики для разных p. Видно, что при p = 0.5, погрешность самя низкая."""

current_n = 100
current_p = 0.90


subset = df_clean_no_inf[(df_clean_no_inf["Количество опытов, n"] == current_n) &
                  (df_clean_no_inf["Вероятность успеха, p"] == current_p)]


#subset = subset.sort_values(by="Количество успехов, m")


plt.figure(figsize=(10, 6))

# График биномиального распределения
plt.plot(subset["Количество успехов, m"],
         subset["Вероятность P(X=m) по формуле Бернулли"],
         label="График биномиального распределения",
         color="blue", marker="o", markersize=3, alpha=0.6)

# График нормального распределения
plt.plot(subset["Количество успехов, m"],
         subset["Вероятность P(X=m) по формуле нормального распределения"],
         label="График нормального",
         color="red", linestyle="--", linewidth=2)

plt.title(f"Сравнение распределений при: n={current_n}, p={current_p}")
plt.xlabel("Количество успехов, m")
plt.ylabel("Вероятность события, P(X=m)")
plt.legend()
plt.grid(True, alpha=0.3)

plt.show()


# График погрешности
df1 = df_clean_no_inf[df_clean_no_inf["Количество опытов, n"] == current_n]
df1 = df1[df1["Вероятность успеха, p"] == current_p]

plt.figure(figsize=(10, 6))
plt.plot(df1["Количество успехов, m"], df1["Относительная погрешность биномиального относительно нормального"] , label="Относительная погрешность биномиального относительно нормального при n = 100, p = 0.95")

plt.title(f"Погрешность при: n={current_n}, p={current_p}")

plt.xlabel("Количество успехов, m")
plt.ylabel("Погрешность")
plt.grid(True, alpha=0.3)

plt.show()

current_n = 100
current_p = 0.5


subset = df_clean_no_inf[(df_clean_no_inf["Количество опытов, n"] == current_n) &
                  (df_clean_no_inf["Вероятность успеха, p"] == current_p)]


#subset = subset.sort_values(by="Количество успехов, m")


plt.figure(figsize=(10, 6))

# График биномиального распределения
plt.plot(subset["Количество успехов, m"],
         subset["Вероятность P(X=m) по формуле Бернулли"],
         label="График биномиального распределения",
         color="blue", marker="o", markersize=3, alpha=0.6)

# График распределения Пуассона
plt.plot(subset["Количество успехов, m"],
         subset["Вероятность P(X=m) по формуле нормального распределения"],
         label="График нормального",
         color="red", linestyle="--", linewidth=2)

plt.title(f"Сравнение распределений при: n={current_n}, p={current_p}")
plt.xlabel("Количество успехов, m")
plt.ylabel("Вероятность события, P(X=m)")
plt.legend()
plt.grid(True, alpha=0.3)

plt.show()


# График погрешности
df1 = df_clean_no_inf[df_clean_no_inf["Количество опытов, n"] == current_n]
df1 = df1[df1["Вероятность успеха, p"] == current_p]

plt.figure(figsize=(10, 6))
plt.plot(df1["Количество успехов, m"], df1["Относительная погрешность биномиального относительно нормального"] , label="Относительная погрешность биномиального относительно нормального при n = 100, p = 0.95")

plt.title(f"Погрешность при: n={current_n}, p={current_p}")

plt.xlabel("Количество успехов, m")
plt.ylabel("Погрешность")
plt.grid(True, alpha=0.3)

plt.show()

# График с другим масштабом
df1 = df_clean_no_inf[df_clean_no_inf["Количество опытов, n"] == current_n]
df1 = df1[df1["Вероятность успеха, p"] == current_p]

plt.figure(figsize=(10, 6))
plt.plot(df1["Количество успехов, m"], df1["Относительная погрешность биномиального относительно нормального"] , label="Относительная погрешность биномиального относительно нормального при n = 100, p = 0.95")

plt.ylim(0, 5)
plt.grid(True, alpha=0.3)

plt.title(f"Погрешность при: n={current_n}, p={current_p}. Другой масштаб y")

plt.xlabel("Количество успехов, m")
plt.ylabel("Погрешность")
plt.grid(True, alpha=0.3)

plt.show()

current_n = 100
current_p = 0.25


subset = df_clean_no_inf[(df_clean_no_inf["Количество опытов, n"] == current_n) &
                  (df_clean_no_inf["Вероятность успеха, p"] == current_p)]


#subset = subset.sort_values(by="Количество успехов, m")


plt.figure(figsize=(10, 6))

# График биномиального распределения
plt.plot(subset["Количество успехов, m"],
         subset["Вероятность P(X=m) по формуле Бернулли"],
         label="График биномиального распределения",
         color="blue", marker="o", markersize=3, alpha=0.6)

# График распределения Пуассона
plt.plot(subset["Количество успехов, m"],
         subset["Вероятность P(X=m) по формуле нормального распределения"],
         label="График нормального распределения",
         color="red", linestyle="--", linewidth=2)

plt.title(f"Сравнение распределений при: n={current_n}, p={current_p}")
plt.xlabel("Количество успехов, m")
plt.ylabel("Вероятность события, P(X=m)")
plt.legend()
plt.grid(True, alpha=0.3)

plt.show()


# График погрешности
df1 = df_clean_no_inf[df_clean_no_inf["Количество опытов, n"] == current_n]
df1 = df1[df1["Вероятность успеха, p"] == current_p]

plt.figure(figsize=(10, 6))
plt.plot(df1["Количество успехов, m"], df1["Относительная погрешность биномиального относительно нормального"] , label="Относительная погрешность биномиального относительно нормального при n = 100, p = 0.95")

plt.title(f"Погрешность при: n={current_n}, p={current_p}")

plt.xlabel("Количество успехов, m")
plt.ylabel("Погрешность")
plt.grid(True, alpha=0.3)

plt.show()


#
df1 = df_clean_no_inf[df_clean_no_inf["Количество опытов, n"] == current_n]
df1 = df1[df1["Вероятность успеха, p"] == current_p]
df1 = df1[df1["Количество успехов, m"] > 5]


plt.figure(figsize=(10, 6))
plt.plot(df1["Количество успехов, m"], df1["Относительная погрешность биномиального относительно нормального"] , label="Относительная погрешность биномиального относительно нормального при n = 100, p = 0.95")

plt.title(f"Погрешность при: n={current_n}, p={current_p}. Другой масштаб погрешности")

plt.xlabel("Количество успехов, m")
plt.ylabel("Погрешность")
plt.grid(True, alpha=0.3)

plt.show()

"""## 3 Как влияет на результаты увеличение значения n?

Из хитмапов в заданиях 1 и 2 видно, что с увеличением n погрешность уменьшается.
"""

import seaborn as sns

viz_data = error_df.reset_index()

pivot_table = viz_data.pivot(
    index="Количество опытов, n",
    columns="Вероятность успеха, p",
    values=("Относительная погрешность биномиального относительно Пуассона", "mean")
)

plt.figure(figsize=(10, 15))
sns.heatmap(pivot_table, annot=True, fmt=".3f", cmap="RdYlGn_r", vmax=1.0)


plt.title("Средняя относительная погрешность приближения Пуассона")
plt.show()

pivot_table = viz_data.pivot(
    index="Количество опытов, n",
    columns="Вероятность успеха, p",
    values=("Относительная погрешность биномиального относительно нормального", "mean")
)

plt.figure(figsize=(10, 15))
sns.heatmap(pivot_table, annot=True, fmt=".3f", cmap="RdYlGn_r", vmax=1.0)


plt.title("Средняя относительная погрешность ")
plt.show()

"""# Тест. Потом убрать

Эту часть взял у Софьи. Хочу разобраться, что она тут делала.
"""

df_analysis = df.groupby(['Количество опытов, n', 'Вероятность успеха, p']).agg({
    'Относительная погрешность биномиального относительно Пуассона': ['mean', 'std'],
    'Относительная погрешность биномиального относительно нормального': ['mean', 'std'],
    'Относительная погрешность Пуассона относительно нормального': ['mean', 'std']
}).reset_index()
df_analysis

poisson_p_values = [0.0005, 0.005, 0.05]
poisson_df = df_analysis[df_analysis['Вероятность успеха, p'].isin(poisson_p_values)]

plt.figure(figsize=(12, 6))
for p_val in poisson_p_values:
    subset = poisson_df[poisson_df['Вероятность успеха, p'] == p_val]
    plt.plot(subset['Вероятность успеха, p'], subset[('Относительная погрешность биномиального относительно Пуассона', 'mean')],
             label=f'p={p_val}', linewidth=2)

plt.xlabel('(n)')
plt.ylabel('avg relative error')
plt.title('The accuracy of the Poisson ')
plt.legend()
plt.grid(True)
plt.ylim(0, 1000)
plt.show()

import math
n = 100
p = 0.8
temp = scipy.stats.binom(n,p)
print(temp.cdf(101))

temp1 = scipy.stats.poisson(n*p)
print(temp1.cdf(1/(n*p)))

# математическое ожидание
mean = n*p
# дисперсия
variance = n*p*(1-p)
# нормальное распределение с мат. ожиданием np и ско npq. Второй параметр тут - ско, а не дисперсия
temp2 = scipy.stats.norm(mean,math.sqrt(variance))
print(temp2.cdf(mean+3*math.sqrt(variance))-temp2.cdf(mean-3*math.sqrt(variance)))

import numpy as np
from scipy.stats import binom
import matplotlib.pyplot as plt
fig, ax = plt.subplots(1, 1)

n, p = 1000, 0.5
mean, var, skew, kurt = binom.stats(n, p, moments='mvsk')

x = np.arange(binom.ppf(0.01, n, p),
              binom.ppf(0.99, n, p))
ax.plot(x, binom.pmf(x, n, p), 'bo', ms=8, label='binom pmf')
ax.vlines(x, 0, binom.pmf(x, n, p), colors='b', lw=5, alpha=0.5)

rv = binom(n, p)
ax.vlines(x, 0, rv.pmf(x), colors='k', linestyles='-', lw=1,
        label='frozen pmf')
ax.legend(loc='best', frameon=False)
plt.show()