# -*- coding: utf-8 -*-
"""ТВиМС 3 практическая  работа.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KA-eEw0k-9aK6_LgufbfmG7y257k8G8u

# Заревич Михаил 513-2
Вариант 179

Нулевая гипотеза - случайная величина имеет равномерное распределение.

## Анализ выборки.

Документация на критерий Колмогорова-Смирнова - https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kstest.html

Статистика (распределение) Колмогорова-Смирнова - https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kstwo.html

Критерий хи-квадрат - https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.chisquare.html

Распределение хи-квадрат - https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.chi2.html#scipy.stats.chi2
"""

import pandas as pd
import itertools
import scipy.stats
import math
import matplotlib.pyplot as plt

# Уровни значимости Significance level
alphas = [0.005, 0.01, 0.05]
"""Уровни значимости Significance level"""

# Соответствующие им доверительные вероятности Confidence level
gammas = [0.995, 0.99, 0.95]
"""Доверительные вероятности Confidence level"""

# по умолчанию первая строчка csv файла записывается в заголовок колонки
# чтобы этого не было надо написать header = None
df = pd.read_csv("/content/v179.csv", header =None)

df = df.sort_values(by = [0]).reset_index()
df = df.rename(columns={0: "Значения"})
df

# Значения разбросаны в диапазоне от 0 до 225.
# Диапазон можно разделить на 15 интервалов и посмотреть, сколько значений будет в каждом из них.
bins = pd.cut(df["Значения"], 15)
bins

df["Интервалы"] = bins
df

# Группировка значений по интервалам.
temp = df.groupby('Интервалы')

# Группированный статистический ряд абсолютных частот.
Series = temp.agg({'Интервалы': 'count'})

print(Series)

# Группированный статистический ряд абсолютных частот.
Series = Series.rename(columns={"Интервалы": "Количество значений, попавших в интервал"})
temp = df['Интервалы'].unique()
Series["Интервалы"] = temp

Series

import seaborn as sns

x = Series["Интервалы"]
y = Series["Количество значений, попавших в интервал"]
sns.barplot(x=x, y=y)
plt.title("Группированный статистический ряд абсолютных частот.")
plt.show()

df['Значения'].plot(kind='hist', bins=20, title='Значения')
plt.gca().spines[['top', 'right',]].set_visible(False)

print("Выборочное математическое ожидание: ", df["Значения"].mean())
print("Выборочная дисперсия: ", df["Значения"].var())
print("Выборочное ско: ", df["Значения"].std())
print("Выборочный коэффициент ассиметрии: ", df["Значения"].skew())
print("Выборочный эксцесс: ", df["Значения"].kurtosis())

"""**Вывод.**

На основании вида графика можно выдвинуть гипотезу - случайная величина имеет равномерное распределение.

## Проверка гипотезы по критерию Колмогорова-Смирнова.

Этот критерий предназначен для проверки гипотез о
принадлежности анализируемой выборки некоторому известному закону
распределения.


Используем one-sample test.

This test compares the underlying distribution F(x) of a sample against a given continuous distribution G(x).
"""

# Сравнивает функцию распределения выборки, стоящую на первом месте с теоретической функцией распределения, стоящей на втором месте.
# Нужно использовать df["Значения"].
# Series["Количество значений, попавших в интервал."] тут не подойдёт, так как это плотность распределения.
# вместо "uniform" можно написать scipy.stats.uniform.cdf
# args() содержит параметры распределения.
# в случае равномерного распределения первый параметр - это нижняя граница, второй - расстояние до верхней границы.
# В документации про это не написано.
# По умолчанию равномерное распределение будет с параметрами (0, 1). Можно и задать и другие значения.
# У меня в df["Значения"] значения от 0 до 225, нужно поставить их
# либо отнормировать в диапазон (0, 1) используя temp = df[0]/225, тогда args можно не писать.
# Значения pvalue будут одинаковыми
# alternative='two-sided' - это тот способ, который мы проходили на лецкии
# d0 = max(d+,d-)

# Если, например, распределение будет U(25, 250), то будет args=(25, 225)


KSTest1 = scipy.stats.kstest(df["Значения"] , "uniform", args=(0, 225), alternative='two-sided')

temp = df["Значения"]/225
KSTest2 = scipy.stats.kstest(temp , "uniform")


print(KSTest1)
print(KSTest2)
print("Наблюдаемое значение критерия d0: ", KSTest1[0])
print("P-значение: ", KSTest1[1])

"""**Вывод.**

Проверка гипотезы по наблюдаемому значению критерия.

Критерий Колмогорова-Смирнова имеет правостороннюю критическую область $D> d_\alpha$. Следовательно, нулевая гипотеза $H_0$ принимается при
$d_0<d_\alpha$

"""

print("Наблюдаемое значение критерия d0:", KSTest1[0])
print("\n")
for i in range(len(gammas)):
    d_alpha = scipy.stats.kstwo.ppf(gammas[i], len(df))
    print("Критическое значение d_alpha: ", d_alpha)
    if (KSTest1[0] < d_alpha):
        print("d_0 < d_alpha")
        print("Гипотеза принимается с доверительной вероятностью", gammas[i])
        print("\n")

"""
Проверка через pvalue.


Из документации:
We choose a confidence level of 95%; that is, we will reject the null hypothesis in favor of the alternative if the p-value is less than 0.05.


Т.е. нулевая гипотеза отвергается, если pvalue меньше заданного уровня значимости, и принимается - если больше.

Максимальное значение уровня значимости у нас - 0,05. Pvalue больше него, значит при всех уровнях значимости нулевую гипотезу можно принять.
"""

print("p-значение:", KSTest1[1])
print("\n")

for i in range(len(alphas)):
    print("Уровень значимости: ", alphas[i])
    if (KSTest1[1] > alphas[i]):
        print("p-value > alpha")
        print("Гипотеза принимается с доверительной вероятностью",  gammas[i])
        print("\n")

"""## Проверка гипотезы по критерию хи квадрат.

The chi-square test tests the null hypothesis that a given set of categorical data has the given frequencies.

Параметры функции.
```
f_obs = array_like. Observed frequencies in each category.
f_exp = array_like, optional. Expected frequencies in each category.
Не поддерживает callable. Т.е. тут нельзя написать scipy.stats.uniform
chisquare(f_obs, f_exp=None ...)
```

1 вариант.

Из документации: f_exp - Expected frequencies in each category. By default, the categories are assumed to be equally likely.

Т.е. если не задавать этот параметр, наша выборка будет сравниваться с равномерным распределением.

Про ddof подробнее в следующей текстовой ячейке.

ddof - int, optional - “Delta degrees of freedom”: adjustment to the degrees of freedom for the p-value. The p-value is computed using a chi-squared distribution with k - 1 - ddof degrees of freedom, where k is the number of categories. The default value of ddof is 0.
"""

Chi_test = scipy.stats.chisquare(Series["Количество значений, попавших в интервал"],ddof = 2)
print(Chi_test)
print("Наблюдаемое значение критерия d0: ", Chi_test[0])
print("P-значение: ", Chi_test[1])

"""**Вывод.**

Проверка по наблюдаемому значению критеория.

Если $\chi^2_0 < \chi^2_{1-\alpha, k-1}$, то нулевая гипотеза $H_0$ принимается. Иначе нулевая гипотеза отклоняется.

См. Теория вероятностей и математическая статистика, Фадеева, Лебедев. стр 354 и 357.

Значение двух параметров равномерного распределения 0 и 225 я нашёл из выборки, они не были даны заранее. Поэтому количество степеней свободы распределения хи-квадрат нужно уменьшить на 2, т.е. $\chi^2_0 < \chi^2_{1-\alpha, k-1-r}$.
"""

print("Наблюдаемое значение критерия d0:", Chi_test[0])
print("\n")
for i in range(len(gammas)):
    d_alpha = scipy.stats.chi2.ppf(gammas[i], len(Series)-1-2)
    print("Критическое значение d_alpha: ", d_alpha)
    if (Chi_test[0] < d_alpha):
        print("d_0 < d_alpha")
        print("Гипотеза принимается с доверительной вероятностью", gammas[i])
        print("\n")

"""Проверка через p-значение будет такой же."""

print("p-значение:", Chi_test[1])
print("\n")

for i in range(len(alphas)):
    print("Уровень значимости: ", alphas[i])
    if (Chi_test[1] > alphas[i]):
        print("p-value > alpha")
        print("Гипотеза принимается с доверительной вероятностью",  gammas[i])
        print("\n")

"""2 вариант.

Параметр f_exp можно задать вручную.

Мы хотим проверить, является ли распределение равномерным. Используя закон распределения равномерного распределения, составим предполагаемый статистический ряд абсолютных частот.


Series["Количество значений, попавших в интервал"] - это будут наши ni. Поскольку мы хотим проверить равномерное распределение, pi - вероятность попадания в каждый из 15 интервалов будет равна 1/15




"""

pi = 1/15
n = len(df)
temp = n*pi
ExpectedFrequencies = [temp for i in range(15)]
ExpectedFrequencies

# сравниваем ряд ni с n*pi
print(scipy.stats.chisquare(Series["Количество значений, попавших в интервал"], ExpectedFrequencies, ddof=2))

"""**Вывод.**

Наблюдаемое значение критерия и pvalue получились такими же, как и в первом варианте.

"""