# -*- coding: utf-8 -*-
"""ТВиМС 5 практическая работа.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PB_iVLg3bup8LA6VjSE3lLatXatePOcA

# Заревич Михаил 513-2
Вариант 169

## Подготовка данных
"""

import pandas as pd
import scipy
import numpy as np
import sympy
import math


import matplotlib.pyplot as plt
import seaborn as sns

# по умолчанию первая строчка csv файла записывается в заголовок колонки
# чтобы этого не было надо написать header = None
df = pd.read_csv("/content/v169.csv", header = None)

df = df.rename(columns={0: "X"})
df = df.rename(columns={1: "Y"})

df

"""Корреляционная таблица"""

# FrequencyTable
ft = pd.crosstab(df["X"], df["Y"])
ft

"""Посчитаем выборочные характеристики связи двух случайных величин.

Выборочная ковариация:
$$ COV(\hat{X}, \hat{Y}) = \frac{1}{n} \sum_{i=1}^k\sum_{j=1}^l \hat{x_i} \hat{y_j} \nu_{ij}- \overline{x}\overline{y}$$

Выборочный коффициент корреляции:
$$ r_{xy} = \frac{COV(X,Y)}{\sigma_x\sigma_y} $$

Коэффициент детерминации
$$ R_{xy} = r_{xy}^2 $$
"""

COV = 0
n = 0 # сумма абсолютных частот, она должна быть равна len(df) 5000
# цикл по строкам
for xi in range(len(ft.index)):
    # цикл по столбцам
    for yj in range(len(ft.columns)):

        #ft.index[xi] - Значение СВ X
        #ft.columns[yj] - Значение СВ Y
        # ft.loc[ft.index[xi]][ft.columns[yj]] - Абсолютная частота

        COV += ft.index[xi]*ft.columns[yj]*ft.loc[ft.index[xi]][ft.columns[yj]]
        n+=ft.loc[ft.index[xi]][ft.columns[yj]] # проверка, нужно, чтобы сумма была равна len(df) 5000

COV /= len(df)
COV -= df["X"].mean()*df["Y"].mean()

print(n)

print("Выборочная ковариация: ", COV)
rxy = COV/(df["X"].std()*df["Y"].std())
Rxy = rxy**2
print("Выборочный коэффициент корреляции: ", rxy)
print("Выборочный коэффициент детерминации: ", Rxy)

"""В библиотеке pandas есть встроенная функция для поиска коэффицента корреляции, посмотрим, что посчитает она."""

CorrMatrix = df.corr(method='pearson')
plt.figure(figsize=(10, 10))
sns.heatmap(CorrMatrix, annot=True, cmap="coolwarm")
plt.title("Корреляционная матрица.")
plt.show()

CorrMatrix

"""**Вывод**

Мой коэффициент корреляции немного отличается от посчитанного с помощью встроенной функции, но они оба довольно близки к единице. Использование линейной регрессии в этом случае имеет смысл.

## Прямая регрессии Y на Х

Выборочное уравнение прямой регрессии Y на X
$$ g(x) = r_{xy}\frac{\sigma_y}{\sigma_x}(x - \overline{x})+ \overline{y} $$

Найдём коэффициенты прямой с помощью встроенной функции linregress
"""

# slope - наклон прямой - k
# intercept - пересечение с осью x - b
LinRegCoefs = scipy.stats.linregress(df["X"], df["Y"])
LinRegCoefs

"""Получим уравнение в аналитическом виде при помощи sympy"""

x = sympy.Symbol("x")
k = sympy.Symbol("k")
b = sympy.Symbol("b")

expr = (k*x+b).subs([(k, LinRegCoefs[0]), (b, LinRegCoefs[1])])
print("g(x) =", expr)

plt.figure(figsize=(10, 10))

x = np.linspace(1 , 55)

y = 2.95945956332444*x + 1.65559168878472

plt.plot(x, y, label = "Прямая регрессии Y на X")
plt.scatter(df["X"], df["Y"], color='red', label = "Значения выборки")

plt.legend();

plt.show()

"""Построим прямую со значениями, найденными мной."""

plt.figure(figsize=(10, 10))

x = np.linspace(1 , 55)

y = rxy*df["Y"].std()/df["X"].std()*(x - df["X"].mean())+ df["Y"].mean()

plt.plot(x, y, label = "Прямая регрессии Y на X")
plt.scatter(df["X"], df["Y"], color='red', label = "Значения выборки")

plt.legend();

plt.show()

"""Остаточная дисперсия Y на X

$$ Δ = \sigma_{y}^2(1-r_{xy}^2) $$
"""

delta1 = math.sqrt(df["Y"].std())*(1- math.sqrt(rxy))
print("Остаточная дисперсия Y на X", delta1)

"""**Вывод.**

Моя прямая совпадает с прямой, построенной при помощи scipy.

## Прямая регрессии X на Y

Выборочное уравнение прямой регрессии X на Y
$$ g(y) = r_xy\frac{\sigma_x}{\sigma_y}(y - \overline{y})+ \overline{x} $$
"""

# slope - наклон прямой - k
# intercept - пересечение с осью x - b
LinRegCoefs = scipy.stats.linregress(df["Y"], df["X"])

LinRegCoefs

y = sympy.Symbol("y")
k = sympy.Symbol("k")
b = sympy.Symbol("b")

expr = (k*y+b).subs([(k, LinRegCoefs[0]), (b, LinRegCoefs[1])])
print("g(y) =", expr)

plt.figure(figsize=(10, 10))

y = np.linspace(-50, 219)

x = 0.22966042095497*y + 8.58156406159432

plt.plot(y, x, label="Прямая регрессии X на Y")
plt.scatter(df["Y"], df["X"], color='red', label = "Значения выборки")

plt.legend();

plt.show()

plt.figure(figsize=(10, 10))


y = np.linspace(-50, 219)

x = rxy*df["X"].std()/df["Y"].std()*(y - df["Y"].mean())+ df["X"].mean()

plt.plot(y, x, label="Прямая регрессии X на Y")
plt.scatter(df["Y"], df["X"], color='red', label = "Значения выборки")

plt.legend();

plt.show()

"""Остаточная дисперсия X на Y

$$ Δ = \sigma_{x}^2(1-r_{xy}^2) $$
"""

delta1 = math.sqrt(df["X"].std())*(1- math.sqrt(rxy))
print("Остаточная дисперсия X на Y", delta1)

"""**Вывод.**

Моя прямая совпадает с прямой, построенной при помощи scipy.

## Сравнение прямых регрессии

Построим обе прямые на одном графике.
"""

plt.figure(figsize=(10, 10))

# Линейная регрессия Y на X
x = np.linspace(1 , 55)
y = 2.95945956332444*x + 1.65559168878472

plt.plot(x, y, label = "Прямая регрессии Y на X", color = "blue")


# Линейная регрессия X на Y
y = np.linspace(-50, 219)
x = 0.22966042095497*y + 8.58156406159432
plt.plot(x, y, label="Прямая регрессии X на Y", color="green")

plt.scatter(df["X"], df["Y"], color='red', label = "Значения выборки")

plt.legend();
plt.show()

"""## Линейная регрессиия Y на X при помощи библиотеки sklearn

Посчитаем линейную регрессию с помощью библиотеки sklearn.
"""

# Функция, разбивающая выборку на тренировочную и тестовую
from sklearn.model_selection import train_test_split

# Модели
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import SGDRegressor
from sklearn.tree import DecisionTreeRegressor

# Метрики
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error, mean_squared_error, r2_score

def model_train_test(model, X_train, y_train, X_test, y_test):
  """Обучение и тестирование модели на обучающей и тестовой выборке соответственно.

  Параметры:
   model - Модель, которая обучается и тестируется
   X_train - Объекты обучающей выборки
   y_train - Значения целевой переменной обучающей выборки
   X_test - Объекты тестовой выборки
   y_test - Значения целевой переменной тестовой выборки

   Возвращает:
   model - Обученная модель
   pred - Предсказанные значения
   mae - Метрика MAE
   mape - Метрика MAPE
   mse - Метрика MSE
   rmse - Метрика RMSE
  """

  model.fit(X_train, y_train) # Обучение модели на тренировочной выборке
  pred = model.predict(X_test) # Предсказания модели на тестовой выборке

  # метрики ошибок
  mae = mean_absolute_error(y_test, pred)
  mape = mean_absolute_percentage_error(y_test, pred)
  mse = mean_squared_error(y_test, pred)
  rmse = math.sqrt(mse)
  r2 = r2_score(y_test, pred) # коэффициент детерминации

  print(f"MAE = {mae}; MAPE = {mape}; MSE = {mse}; RMSE = {rmse}; r2 = {r2}")

  return model, pred, mae, mape, mse, rmse, r2

"""По значениям признаков будем предсказывать значения целевой переменной."""

x1 = pd.DataFrame(df["X"]) # Признаки
y1 = pd.DataFrame(df["Y"]) # Значения целевой переменной

X_train, X_test, y_train, y_test = train_test_split(
    x1, y1,
    test_size=0.2, random_state=42
)

LinearModelYX, PredLrYX, MaeLr, MapeLr, MseLr, RmseLr, r2Lr = model_train_test(
    LinearRegression(), # Linear regression по умолчанию использует МНК
    X_train,
    y_train,
    X_test,
    y_test,
)

"""Метрика Mape получилась очень странной."""

plt.figure(figsize=(10, 10))


# Прямая красная линия. Показывает реальные значения.
plt.plot(y_test, y_test, label="Прямая красная линия. Показывает реальные значения Y.", color="red")

# Голубые точки. Показывает, какое значение предсказала модель.
plt.scatter(y_test, PredLrYX, label="Значения X полученные методом наименьших квадратов")


plt.legend();

plt.xlabel("Истинные значения");
plt.ylabel("Предсказания");

"""## Линейная регрессия X на Y при помощи библиотеки sklearn

Чтобы её получить, поменял x и y местами.
"""

y1 = pd.DataFrame(df["X"]) # Целевая переменная
x1 = pd.DataFrame(df["Y"]) # Признаки

X_train, X_test, y_train, y_test = train_test_split(
    x1, y1,
    test_size=0.2, random_state=42
)

LinearModelXY, PredLrXY, MaeLr, MapeLr, MseLr, RmseLr, r2Lr = model_train_test(
    LinearRegression(), # Linear regression по умолчанию использует МНК
    X_train,
    y_train,
    X_test,
    y_test,
)

plt.figure(figsize=(10, 10))


# Прямая красная линия. Показывает реальные значения.
plt.plot(y_test, y_test, label="Прямая красная линия. Показывает реальные значения X", color="red")


# Голубые точки. Показывает, какое значение предсказала модель.
#plt.scatter(y_test, PredLrXY, label="Значения Y полученные методом наименьших квадратов")
plt.scatter(PredLrXY, y_test, label="Значения Y полученные методом наименьших квадратов")


plt.legend();

plt.xlabel("Истинные значения");
plt.ylabel("Предсказания");

"""Построим данные выборки и предсказанные значения на одном графике."""

plt.figure(figsize=(10, 10))


# Прямая красная линия. Показывает реальные значения.
plt.scatter(df["X"], df["Y"], label="Значения выборки", color="red")


# Голубые точки. Показывает, какое значение предсказала модель.
plt.scatter(X_test, PredLrYX, color = "blue", label="Значения X полученные методом наименьших квадратов")
plt.scatter(PredLrXY, y_test, color = "green", label="Значения Y полученные методом наименьших квадратов")


plt.legend();

plt.xlabel("Истинные значения");
plt.ylabel("Предсказания");

"""## Вывод

Некоторые значения, посчитанные мной, например коэффициент корреляции и коэффициент детерминации, немного отличаются от тех, которые были посчитаны библиотеками. Не знаю, почему это произошло, надо, видимо, лучше изучать, как эти библиотеки работают внутри.

Прямые регрессии Y на X и X на Y, если нанести их на один график,  выглядят похожими. Как интерпретировать значения, полученные через sklearn, я не знаю.

В целом, если ситуация такая, что предсказывать значение Y надо только по одной случайной величине, то применение регрессии вполне имеет смысл. Однако я бы посоветовал найти ещё какие-нибудь случайные величины, коррелирующие с Y, и построить множественную линейную регрессию. Она, по моему опыту, работает лучше.

"""