# -*- coding: utf-8 -*-
"""ТВиМС 4 практическая работа.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C_hy0sFsuhcekx2Gu3mAD1uQQDQYv4K1

# Заревич Михаил 513-2

Вариант 169

## Анализ выборки
"""

import pandas as pd
import scipy.stats
import statsmodels.graphics.gofplots
import matplotlib.pyplot as plt
import numpy as np

# Уровни значимости Significance level
alphas = [0.005, 0.01, 0.05]
"""Уровни значимости Significance level"""

# Соответствующие им доверительные вероятности Confidence level
gammas = [0.995, 0.99, 0.95]
"""Доверительные вероятности Confidence level"""

# по умолчанию первая строчка csv файла записывается в заголовок колонки
# чтобы этого не было надо написать header = None
df = pd.read_csv("/content/v169.csv", header = None)

df = df.dropna() # убирает пропуски
df = df.sort_values(by = [0]).reset_index() # Сортировка значений
df = df.rename(columns={0: "Значения"})
df

# Значения разбросаны в диапазоне от -4.052622 до 4.055710.
# Диапазон можно разделить на 20 интервалов и посмотреть, сколько значений будет в каждом из них.
bins = pd.cut(df["Значения"], 20)
bins

df["Интервалы"] = bins
df

# Группировка значений по интервалам.
temp = df.groupby('Интервалы')

# Группированный статистический ряд абсолютных частот.
Series = temp.agg({'Интервалы': 'count'})

print(Series)

# Группированный статистический ряд абсолютных частот.
Series = Series.rename(columns={"Интервалы": "Количество значений, попавших в интервал"})
temp = df['Интервалы'].unique()
Series["Интервалы"] = temp

Series

import seaborn as sns

x1 = Series["Интервалы"]
y = Series["Количество значений, попавших в интервал"]
sns.barplot(x=x1, y=y)
plt.title("Группированный статистический ряд абсолютных частот.")
plt.show()

df['Значения'].plot(kind='hist', bins=20, title='Значения')
plt.gca().spines[['top', 'right',]].set_visible(False)

statsmodels.graphics.gofplots.qqplot(df["Значения"], scipy.stats.norm, line = "45")
plt.title("График квантиль-квантиль.")
plt.show()

print("Выборочное математическое ожидание: ", df["Значения"].mean())
print("Выборочная дисперсия: ", df["Значения"].var())
print("Выборочное ско: ", df["Значения"].std())
print("Выборочный коэффициент ассиметрии: ", df["Значения"].skew())
print("Выборочный эксцесс: ", df["Значения"].kurtosis())

"""**Вывод.**

На основани вида графика и значений выборочных параметров можно выдвинуть гипотезу - случайная величина имеет стандартное нормальное распределение.

## Проверка гипотезы по критерию Шапиро-Уилка

Критерий Шапиро-Уилка проверяет только то, является ли распределение нормальным. Его параметры он не анализирует.
"""

shapiro_test = scipy.stats.shapiro(df["Значения"])
print(shapiro_test)
print("Наблюдаемое значение критерия: ", shapiro_test[0])
print("P-значение: ", shapiro_test[1])

"""Использовать наблюдаемое значение критерия трудно: так как распределение Шапиро-Уилка не имеет формулы, будет невозможно посчитать критическое значение, поэтому будем использовать только p-значение."""

print("p-значение:", shapiro_test[1])
print("\n")

for i in range(len(alphas)):
    print("Уровень значимости: ", alphas[i])
    if (shapiro_test[1] > alphas[i]):
        print("p-value > alpha")
        print("Гипотеза принимается с доверительной вероятностью",  gammas[i])
        print("\n")

"""**Вывод.**

Гипотеза принимается при всех заданных уровнях значимости.

Чтобы проверить именно стандартное нормальное распределение n(0,1) воспользуемся другими критериями.

## Проверка гипотезы по критерию Колмогорова-Смирнова

Проверка происходит аналогично заданию №3.
"""

KSTest = scipy.stats.kstest(df["Значения"] , "norm", args = (0, 1))
print("Наблюдаемое значение критерия: ", KSTest[0])
print("P-значение: ", KSTest[1])

"""**Вывод.**

Проверка гипотезы по наблюдаемому значению критерия.

Критерий Колмогорова-Смирнова имеет правостороннюю критическую область $D> d_\alpha$. Следовательно, нулевая гипотеза $H_0$ принимается при
$d_0<d_\alpha$
"""

print("Наблюдаемое значение критерия d0:", KSTest[0])
print("\n")
for i in range(len(gammas)):
    d_alpha = scipy.stats.kstwo.ppf(gammas[i], len(df))
    print("Критическое значение d_alpha: ", d_alpha)
    if (KSTest[0] < d_alpha):
        print("d_0 < d_alpha")
        print("Гипотеза принимается с доверительной вероятностью", gammas[i])
        print("\n")

"""Проверка через pvalue.

Из документации: We choose a confidence level of 95%; that is, we will reject the null hypothesis in favor of the alternative if the p-value is less than 0.05.

Т.е. нулевая гипотеза отвергается, если pvalue меньше заданного уровня значимости, и принимается - если больше.

"""

print("p-значение:", KSTest[1])
print("\n")

for i in range(len(alphas)):
    print("Уровень значимости: ", alphas[i])
    if (KSTest[1] > alphas[i]):
        print("p-value > alpha")
        print("Гипотеза принимается с доверительной вероятностью",  gammas[i])
        print("\n")

"""## Проверка гипотезы по критерию хи-квадрат

Провека происходит аналогично заданию №3

Проверка по наблюдаемому значению критеория.

Если $\chi^2_0 < \chi^2_{1-\alpha, k-1}$, то нулевая гипотеза $H_0$ принимается. Иначе нулевая гипотеза отклоняется.

См. Теория вероятностей и математическая статистика, Фадеева, Лебедев. стр 354 и 357.

Значение двух параметров нормального распределения 0 и 1 я нашёл из выборки, они не были даны заранее. Поэтому количество степеней свободы распределения хи-квадрат нужно уменьшить на 2, т.е. $\chi^2_0 < \chi^2_{1-\alpha, k-1-r}$.

Зададим вероятности попадания в интервалы.
"""

# Normal distribution
# Нормальное распределение
NormDist = scipy.stats.norm()
ExpectedFrequencies = []

print("Вероятности: ")

for i in temp:
    # вероятность попадания в интервал.
    Pi = NormDist.cdf(i.right)- NormDist.cdf(i.left)
    print(Pi)
    ExpectedFrequencies.append(Pi*len(df))
print()
print("Частоты: ")
for i in ExpectedFrequencies:
    print(i)

"""При таком разбиении у крайних интервалов оказались очень низкие ожидаемые частоты. Для работы критерия хи-квадрат лучше, чтобы эти частоты были больше 5 или 10.
Объединим первые три интервала и последние три, чтобы в них были нормальные частоты.
"""

# observed_frequencies и expeced_frequencies
obs = np.array(Series["Количество значений, попавших в интервал"])
exp = np.array(ExpectedFrequencies)


# Объединение слева
while exp[0] < 10:
    obs[1] += obs[0]
    exp[1] += exp[0]
    # Удаление первого элемента
    obs = obs[1:]
    exp = exp[1:]

# Объединение справа
while exp[-1] < 10:

    obs[-2] += obs[-1]
    exp[-2] += exp[-1]
    # Удаление последнего элемента
    obs = obs[:-1]
    exp = exp[:-1]

for i in exp:
    print(i)

Chi_test = scipy.stats.chisquare(obs, exp, ddof = 2,  sum_check = False)
print(Chi_test)
print("Наблюдаемое значение критерия d0: ", Chi_test[0])
print("P-значение: ", Chi_test[1])

print("Наблюдаемое значение критерия d0:", Chi_test[0])
print("\n")
for i in range(len(gammas)):
    d_alpha = scipy.stats.chi2.ppf(gammas[i], len(Series)-1-2)
    print("Критическое значение d_alpha: ", d_alpha)
    if (Chi_test[0] < d_alpha):
        print("d_0 < d_alpha")
        print("Гипотеза принимается с доверительной вероятностью", gammas[i])
        print("\n")

print("p-значение:", Chi_test[1])
print("\n")

for i in range(len(alphas)):
    print("Уровень значимости: ", alphas[i])
    if (Chi_test[1] > alphas[i]):
        print("p-value > alpha")
        print("Гипотеза принимается с доверительной вероятностью",  gammas[i])
        print("\n")